version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: 1234
      DB_DIALECT: postgres
      DB_NAME_DEVELOPMENT: postgres
      JWTKEY: random_secret_key
      TOKEN_EXPIRATION: 48h
      BEARER: Bearer
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
