version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file: .env.production
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

secrets:
  db_password:
    file: ./db_password.txt

volumes:
  postgres_data:
